using System;
using Microsoft.Xna.Framework;

namespace forgotten.Desktop
{
    public class EncounterPane : Pane
    {
        AnimatedAsset self;
        private int padding = 32;

        public EncounterPane(System system)
        {
            self = AddChild("self", new AnimatedAsset("autogenerated/self_bored"));
            //dialogRect = AddChild(self, new Rect)
        }

        public override void Draw(Vector2 targetSize)
        {
            DrawColoredRect(new Vector2(padding, targetSize.Y - padding - self.Height()),
                            new Vector2(targetSize.X - 2 * padding, self.Height()),
                            Color.LightBlue);
        }

        public override void Update(Vector2 targetSize, GameTime gameTime)
        {
            self.Position = new Vector2(2*padding, targetSize.Y - self.Height() - 2*padding);
        }
    }
}
