using System;
using Microsoft.Xna.Framework;

namespace forgotten.Desktop
{
    public class EncounterPane : Pane
    {
        AnimatedAsset self;
        AnimatedAsset alien;
        TextAsset alienText;
        private int padding = 16;

        public EncounterPane(System system)
        {
            self = AddChild("self", new AnimatedAsset("autogenerated/self_bored"));
            alien = AddChild("alien", new AnimatedAsset("autogenerated/alien_idle"));
            alienText = AddChild("alienText", new TextAsset());
            alienText.Text = @"Halt, Terran!

You have ventured into *blurp* Korgat space and are under our *blurp* jurisdication.

State your business or be destroyed.";
        }

        public override void Draw(Vector2 targetSize)
        {
            DrawColoredRect(new Vector2(padding, padding),
                            new Vector2(targetSize.X - 2 * padding, self.Height()),
                            Color.MediumBlue);


            DrawColoredRect(new Vector2(padding, targetSize.Y - padding - self.Height()),
                            new Vector2(targetSize.X - 2 * padding, self.Height()),
                            Color.LightBlue);
        }

        public override void Update(Vector2 targetSize, GameTime gameTime)
        {
            alienText.Position = new Vector2(2 * padding, 2 * padding);
            alienText.MaxLineLength = (int)(targetSize.X - 4 * padding - alien.Width());
            alien.Position = new Vector2(targetSize.X - 2 * padding - alien.Width(), 2 * padding);

            self.Position = new Vector2(2*padding, targetSize.Y - self.Height() - 2*padding);
        }
    }
}
