using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace forgotten.Desktop
{
    public class SpacePortPane : Pane
    {
        private LayeredAsset spacePort;

        public SpacePortPane()
        {
            var label = new TextAsset("Space Port");
            AddChild("spacePortLabel", label);

            spacePort = new LayeredAsset("autogenerated/space_port");
            spacePort.Position = new Vector2(200, 100);
            spacePort.SetOutlinedPart("cinema", "Space Tavern");
            AddChild("spacePortLayered", spacePort);
        }

        public override void Draw(Vector2 targetSize)
        {
            DrawColoredRect(Vector2.Zero,
                            targetSize,
                            Color.Black);
        }

        public override void Update(Vector2 targetSize, GameTime gameTime)
        {
        }
    }
}
