using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace forgotten.Desktop
{
    public class SpacePortPane : Pane
    {
        private LayeredAsset spacePort;

        public SpacePortPane()
        {
            var label = new TextAsset("Space Port");
            AddChild("spacePortLabel", label);

            spacePort = new LayeredAsset("autogenerated/space_port");
            spacePort.Position = new Vector2(200, 100);
            spacePort.SetOutlinedPart("cinema", "Space Tavern");
            spacePort.SetOutlinedPart("dollar_dream", "Trader");
            AddChild("spacePortLayered", spacePort);
        }

        public override void Draw(Vector2 targetSize)
        {
            DrawColoredRect(Vector2.Zero,
                            targetSize,
                            Color.Black);
        }

        public override void Update(Vector2 targetSize, GameTime gameTime)
        {
            MouseState ms = Mouse.GetState();
            mouseTracker().Update(ms);

            if (mouseTracker().WasPressed())
            {
                if (spacePort.IsPartHovered("cinema"))
                {
                    Console.WriteLine("enter space tavern");
                }
                else if (spacePort.IsPartHovered("dollar_dream"))
                {
                    PaneStack.Instance.Push(new TraderPane());
                    Console.WriteLine("enter trader");
                }
            }
        }
    }
}
